# Generated by Django 5.2.1 on 2025-07-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtbooking',
            old_name='book_for_six_months',
            new_name='book_for_four_weeks',
        ),
    ]
