# Generated by Django 5.2.1 on 2025-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_book_for_six_months_courtbooking_book_for_four_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbooking',
            name='on_amount',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
