# Generated by Django 5.2.1 on 2025-06-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
