# Generated by Django 5.2.1 on 2025-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_courtbooking_on_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EMAIL_HOST_PASSWORD',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='EMAIL_HOST_USER',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
