# Generated by Django 4.1.13 on 2025-06-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_court_test_alter_contactus_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbooking',
            name='book_for_six_months',
            field=models.BooleanField(default=False),
        ),
    ]
