# Generated by Django 4.1.13 on 2025-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_courtbooking_book_for_six_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
