# Generated by Django 5.2.1 on 2025-08-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_email_host_password_user_email_host_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbooking',
            name='parent_booking',
            field=models.CharField(null=True),
        ),
    ]
