# Generated by Django 4.1.13 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_court_end_time_court_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbooking',
            name='total_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
