# Generated by Django 5.2.1 on 2025-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_courtbooking_parent_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtbooking',
            name='parent_booking',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
