# Generated by Django 5.2.1 on 2025-06-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('court_number', models.CharField(max_length=30)),
                ('court_fee_hrs', models.CharField(max_length=20)),
                ('tax', models.CharField()),
                ('cc_fees', models.CharField()),
                ('availability', models.BooleanField(default=False)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.location')),
            ],
            bases=('user.basemodel', models.Model),
        ),
    ]
