# Generated by Django 4.1.13 on 2025-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_courtbooking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
