# Generated by Django 5.2.1 on 2025-06-12 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_phone_court'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_time', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
