# Generated by Django 5.2.1 on 2025-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_location_alter_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
