# Generated by Django 5.2.1 on 2025-07-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_location_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_booked',
        ),
    ]
