# Generated by Django 5.2.1 on 2025-06-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_contactus'),
        ('user', '0011_courtbooking_created_at_courtbooking_updated_at_and_more'),
    ]

    operations = [
    ]
