# Generated by Django 5.2.1 on 2025-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_location_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
