# Generated by Django 5.2.1 on 2025-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_location_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
