# Generated by Django 5.2.1 on 2025-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_payment_booking_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtbooking',
            name='stripe_payment_intent_id',
        ),
    ]
